In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Intellipat\2) Python intellipat\1) Aditya Code jupyter files\4. Mathematics\2. Statistics\housing (1).csv")

In [3]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

# Find the average sale price of house with exactly 3 bedrooms

In [12]:
avg_3bedrooms = df[df['bedrooms'] == 3]

In [13]:
avg_3bedrooms

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
6,1321400060,20140627T000000,257500,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
7,2008000270,20150115T000000,291850,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21603,7852140040,20140825T000000,507250,3,2.50,2270,5536,2.0,0,0,...,8,2270,0,2003,0,98065,47.5389,-121.881,2270,5731
21604,9834201367,20150126T000000,429000,3,2.00,1490,1126,3.0,0,0,...,8,1490,0,2014,0,98144,47.5699,-122.288,1400,1230
21607,2997800021,20150219T000000,475000,3,2.50,1310,1294,2.0,0,0,...,8,1180,130,2008,0,98116,47.5773,-122.409,1330,1265
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287

In [16]:
avg_price_of_3_bedrooms = avg_3bedrooms['price'].mean()
avg_price_of_3_bedrooms

np.float64(466232.07949918567)

# What is the Median year built of houses with a waterfront view?

In [26]:
waterfront_view = df[df['waterfront'] == 1]
waterfront_view

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
49,822039084,20150311T000000,1350000,3,2.50,2753,65005,1.0,1,2,...,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
230,8096000060,20150413T000000,655000,2,1.75,1450,15798,2.0,1,4,...,7,1230,220,1915,1978,98166,47.4497,-122.375,2030,13193
246,2025069065,20140929T000000,2400000,4,2.50,3650,8354,1.0,1,4,...,9,1830,1820,2000,0,98074,47.6338,-122.072,3120,18841
264,2123039032,20141027T000000,369900,1,0.75,760,10079,1.0,1,4,...,5,760,0,1936,0,98070,47.4683,-122.438,1230,14267
300,3225069065,20140624T000000,3075000,4,5.00,4550,18641,1.0,1,4,...,10,2600,1950,2002,0,98074,47.6053,-122.077,4550,19508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19984,2025069140,20150317T000000,1898000,3,2.50,2830,4334,3.0,1,4,...,10,2830,0,2006,0,98074,47.6318,-122.071,2830,38211
20325,518500480,20140811T000000,3000000,3,3.50,4410,10756,2.0,1,4,...,11,3430,980,2014,0,98056,47.5283,-122.205,3550,5634
20767,8043700105,20150417T000000,2300000,4,4.00,4360,8175,2.5,1,4,...,10,3940,420,2007,0,98008,47.5724,-122.104,2670,8525
21201,518500460,20141008T000000,2230000,3,3.50,3760,5634,2.0,1,4,...,11,2830,930,2014,0,98056,47.5285,-122.205,3560,5762
21576,9253900271,20150107T000000,3567000,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270

In [27]:
df[df['view'] != 0]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15,9297300055,20150124T000000,650000,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
21,2524049179,20140826T000000,2000000,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
49,822039084,20150311T000000,1350000,3,2.50,2753,65005,1.0,1,2,...,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
58,7922800400,20140827T000000,951000,5,3.25,3250,14342,2.0,0,4,...,8,3250,0,1968,0,98008,47.5880,-122.116,2960,11044
60,1516000055,20141210T000000,650000,3,2.25,2150,21235,1.0,0,3,...,8,1590,560,1959,0,98166,47.4336,-122.339,2570,18900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21554,2855000110,20140808T000000,388000,3,2.50,2198,6222,2.0,0,2,...,8,2198,0,2010,0,98198,47.3906,-122.304,2198,7621
21576,9253900271,20150107T000000,3567000,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
21579,7011201004,20140529T000000,645000,3,3.25,1730,1229,2.0,0,2,...,9,1320,410,2008,0,98119,47.6374,-122.369,1710,1686
21593,8672200110,20150317T000000,1088000,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21598,8956200760,20141013T000000,541800,4,2.50,3118,7866,2.0,0,2,...,9,3118,0,2014,0,98001,47.2931,-122.264,2673,6500

In [29]:
median_yrbulit_waterfrontview = df[df['waterfront'] == 1]['yr_built'].median()
median_yrbulit_waterfrontview

1960.0

# Find the maximum living space built (sqft_living) among houses built after the year 2000

In [33]:
builtyr_after_2000 = df[df['yr_built'] > 2000]
builtyr_after_2000

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
5,7237550310,20140512T000000,1225000,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
9,3793500160,20150312T000000,323000,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570
29,1873100390,20150302T000000,719000,4,2.50,2570,7173,2.0,0,0,...,8,2570,0,2005,0,98052,47.7073,-122.110,2630,6026
30,8562750320,20141110T000000,580500,3,2.50,2320,3980,2.0,0,0,...,8,2320,0,2003,0,98027,47.5391,-122.070,2580,3980
31,2426039314,20141201T000000,280000,2,1.50,1190,1265,3.0,0,0,...,7,1190,0,2005,0,98133,47.7274,-122.357,1390,1756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [36]:
builtyr_after_2000['sqft_living'].max()

9890

# Count how many houses have more than 2 floors and condition rating >= 4

In [54]:
Ques4 = df[(df['floors'] > 2) & (df['condition'] >= 4)]
Ques4

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
518,4386700135,20141114T000000,2250000,4,2.25,4760,8036,2.5,0,0,...,9,3390,1370,1916,0,98112,47.6415,-122.285,2950,9323
759,770000045,20141024T000000,405600,5,1.50,2830,4000,2.5,0,0,...,8,2830,0,1918,0,98118,47.5132,-122.262,1480,4000
960,7578200310,20141112T000000,650000,4,2.00,2208,5000,3.0,0,0,...,8,2208,0,1917,0,98116,47.5711,-122.383,1760,5000
1296,5458800125,20140514T000000,925000,4,2.50,2190,7350,2.5,0,0,...,8,2190,0,1958,0,98040,47.5786,-122.236,1880,7350
1337,7234600796,20141126T000000,495000,2,1.75,1850,2530,2.5,0,0,...,7,1850,0,1903,0,98122,47.6106,-122.310,1500,1795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18409,2397101606,20141208T000000,2630000,6,4.75,5540,7200,2.5,0,2,...,11,3950,1590,1909,0,98119,47.6361,-122.366,2930,7200
18477,1346300150,20141020T000000,3300000,8,4.00,7710,11750,3.5,0,0,...,12,6090,1620,1904,0,98112,47.6263,-122.314,4210,8325
18631,1337800665,20140811T000000,1325000,4,3.25,2850,4800,2.5,0,0,...,10,2700,150,1905,0,98112,47.6292,-122.312,2850,4800
19068,6613001241,20140811T000000,1415000,4,3.00,3110,4408,2.5,0,3,...,10,2510,600,1931,0,98105,47.6583,-122.270,3250,5669
19272,1337300145,20140721T000000,1800000,4,2.50,3320,8325,2.5,0,0,...,10,3320,0,1905,0,98112,47.6263,-122.314,3680,6050

In [53]:
Ques4.count()

id               76
date             76
price            76
bedrooms         76
bathrooms        76
sqft_living      76
sqft_lot         76
floors           76
waterfront       76
view             76
condition        76
grade            76
sqft_above       76
sqft_basement    76
yr_built         76
yr_renovated     76
zipcode          76
lat              76
long             76
sqft_living15    76
sqft_lot15       76
dtype: int64

# Q5) Calculate the average no of bathrooms for houses priced above $1,000,000

In [55]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [64]:
million_dollars = df[df['price'] > 1000000]
million_dollars

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
5,7237550310,20140512T000000,1225000,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
21,2524049179,20140826T000000,2000000,3,2.75,3050,44867,1.0,0,4,...,9,2330,720,1968,0,98040,47.5316,-122.233,4110,20336
49,822039084,20150311T000000,1350000,3,2.50,2753,65005,1.0,1,2,...,9,2165,588,1953,0,98070,47.4041,-122.451,2680,72513
69,1802000060,20140612T000000,1325000,5,2.25,3200,20158,1.0,0,0,...,8,1600,1600,1965,0,98004,47.6303,-122.215,3390,20158
70,1525059190,20140912T000000,1040000,5,3.25,4770,50094,1.0,0,0,...,11,3070,1700,1973,0,98005,47.6525,-122.160,3530,38917
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21590,7430200100,20140514T000000,1222500,4,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21593,8672200110,20150317T000000,1088000,5,3.75,4170,8142,2.0,0,2,...,10,4170,0,2006,0,98056,47.5354,-122.181,3030,7980
21597,191100405,20150421T000000,1575000,4,3.25,3410,10125,2.0,0,0,...,10,3410,0,2007,0,98040,47.5653,-122.223,2290,10125
21600,249000205,20141015T000000,1537000,5,3.75,4470,8088,2.0,0,0,...,11,4470,0,2008,0,98004,47.6321,-122.200,2780,8964
21606,7936000429,20150326T000000,1007500,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200

In [65]:
million_dollars['bathrooms'].mean()

np.float64(3.166211604095563)

In [71]:
df['bathrooms'].unique()

array([1.  , 2.25, 3.  , 2.  , 4.5 , 1.5 , 2.5 , 1.75, 2.75, 3.25, 4.  ,
       3.5 , 0.75, 4.75, 5.  , 4.25, 3.75, 0.  , 1.25, 5.25, 6.  , 0.5 ,
       5.5 , 6.75, 5.75, 8.  , 7.5 , 7.75, 6.25, 6.5 ])

In [77]:
df['bathrooms'].value_counts()

bathrooms
2.50    5380
1.00    3852
1.75    3048
2.25    2047
2.00    1930
1.50    1446
2.75    1185
3.00     753
3.50     731
3.25     589
3.75     155
4.00     136
4.50     100
4.25      79
0.75      72
4.75      23
5.00      21
5.25      13
0.00      10
5.50      10
1.25       9
6.00       6
0.50       4
5.75       4
6.75       2
8.00       2
6.25       2
6.50       2
7.50       1
7.75       1
Name: count, dtype: int64

In [72]:
df['bedrooms'].unique()

array([ 3,  2,  4,  5,  1,  6,  7,  0,  8,  9, 11, 10, 33])

In [78]:
df['bedrooms'].value_counts()

bedrooms
3     9824
4     6882
2     2760
5     1601
6      272
1      199
7       38
0       13
8       13
9        6
10       3
11       1
33       1
Name: count, dtype: int64

In [73]:
df[df['bedrooms'] == 33]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15870,2402100895,20140625T000000,640000,33,1.75,1620,6000,1.0,0,0,...,7,1040,580,1947,0,98103,47.6878,-122.331,1330,4700

# Q6) Find the most common grade assigned to the houses

In [70]:
df['grade'].unique()

array([ 7,  6,  8, 11,  9,  5, 10, 12,  4,  3, 13,  1])

In [75]:
df['grade'].value_counts()

grade
7     8981
8     6068
9     2615
6     2038
10    1134
11     399
5      242
12      90
4       29
13      13
3        3
1        1
Name: count, dtype: int64

In [69]:
df['grade'].mode()

0    7
Name: grade, dtype: int64

# Q7) Find the average Lot size (sqft_lot) of houses located in zipcode 98178.

In [80]:
zipcode_98178 = df[df['zipcode'] == 98178]
zipcode_98178

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
117,4060000240,20140623T000000,205425,2,1.00,880,6780,1.0,0,0,...,6,880,0,1945,0,98178,47.5009,-122.248,1190,6780
126,4058801670,20140717T000000,445000,3,2.25,2100,8201,1.0,0,2,...,8,1620,480,1967,0,98178,47.5091,-122.244,2660,8712
273,2976800796,20140925T000000,236000,3,1.00,1300,5898,1.0,0,0,...,7,1300,0,1961,0,98178,47.5053,-122.255,1320,7619
281,6874200960,20150227T000000,170000,2,1.00,860,5265,1.0,0,0,...,6,860,0,1931,0,98178,47.5048,-122.272,1650,8775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20590,179001455,20141107T000000,445000,4,3.25,3450,5000,2.0,0,0,...,8,3450,0,2008,0,98178,47.4925,-122.273,1420,5000
20903,7813500040,20141015T000000,335000,4,2.50,1900,3301,2.0,0,0,...,7,1900,0,2007,0,98178,47.4890,-122.249,1960,3379
21059,4058800439,20140623T000000,664950,5,3.00,3190,7081,1.0,0,2,...,9,1890,1300,2013,0,98178,47.5090,-122.240,2270,7623
21198,4140940130,20141121T000000,450000,3,2.75,2240,3360,2.0,0,0,...,8,2100,140,2014,0,98178,47.4999,-122.232,1790,5873
21591,4140940150,20141002T000000,572000,4,2.75,2770,3852,2.0,0,0,...,8,2770,0,2014,0,98178,47.5001,-122.232,1810,5641

In [81]:
zipcode_98178['sqft_lot'].mean()

np.float64(8309.12213740458)

# Q8) What is the highest sale price among the houses that were renovated (yr_renovated > 0)

In [83]:
df['yr_renovated'].value_counts()

yr_renovated
0       20699
2014       91
2013       37
2003       36
2005       35
        ...
1951        1
1959        1
1948        1
1954        1
1944        1
Name: count, Length: 70, dtype: int64

In [84]:
renovated = df[df['yr_renovated'] > 0]
renovated

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
35,9547205180,20140613T000000,696000,3,2.50,2300,3060,1.5,0,0,...,8,1510,790,1930,2002,98115,47.6827,-122.310,1590,3264
95,1483300570,20140908T000000,905000,4,2.50,3300,10250,1.0,0,0,...,7,2390,910,1946,1991,98040,47.5873,-122.249,1950,6045
103,2450000295,20141007T000000,1088000,3,2.50,2920,8113,2.0,0,0,...,8,2920,0,1950,2010,98004,47.5814,-122.196,2370,8113
115,3626039325,20141121T000000,740500,3,3.50,4380,6350,2.0,0,0,...,8,2780,1600,1900,1999,98117,47.6981,-122.368,1830,6350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19622,7351200295,20150114T000000,1150000,3,1.75,1760,6788,2.0,1,4,...,7,1760,0,1940,1960,98125,47.7336,-122.284,1630,7588
20057,126039256,20140904T000000,434900,3,2.00,1520,5040,2.0,0,0,...,7,1520,0,1977,2006,98177,47.7770,-122.362,1860,8710
20444,4305600360,20150225T000000,500012,4,2.50,2400,9612,1.0,0,0,...,8,1230,1170,1962,2009,98059,47.4799,-122.127,2430,5539
20447,3319500628,20150212T000000,356999,3,1.50,1010,1546,2.0,0,0,...,8,1010,0,1971,2014,98144,47.5998,-122.311,1010,1517
20962,1278000210,20150311T000000,110000,2,1.00,828,4524,1.0,0,0,...,6,828,0,1968,2007,98001,47.2655,-122.244,828,5402

In [85]:
renovated['price'].max()

7700000

# Q9) How many houses have a basement (sqft_basement > 0) and more than 3 bedrooms?

In [88]:
df[(df['sqft_basement'] > 0) & (df['bedrooms'] > 3)]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
5,7237550310,20140512T000000,1225000,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
15,9297300055,20150124T000000,650000,4,3.00,2950,5000,2.0,0,3,...,9,1980,970,1979,0,98126,47.5714,-122.375,2140,4000
20,6300500875,20140514T000000,385000,4,1.75,1620,4980,1.0,0,0,...,7,860,760,1947,0,98133,47.7025,-122.341,1400,4980
32,461000390,20140624T000000,687500,4,1.75,2330,5000,1.5,0,0,...,7,1510,820,1929,0,98117,47.6823,-122.368,1460,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21573,8562790760,20140520T000000,785000,4,3.50,3070,4684,2.0,0,0,...,10,2190,880,2009,0,98027,47.5316,-122.076,2290,2664
21576,9253900271,20150107T000000,3567000,5,4.50,4850,10584,2.0,1,4,...,10,3540,1310,2007,0,98008,47.5943,-122.110,3470,18270
21577,3881900317,20150123T000000,579000,4,3.25,1900,2631,2.0,0,0,...,9,1250,650,2014,0,98144,47.5869,-122.311,1710,4502
21590,7430200100,20140514T000000,1222500,4,3.50,4910,9444,1.5,0,0,...,11,3110,1800,2007,0,98074,47.6502,-122.066,4560,11063
21606,7936000429,20150326T000000,1007500,4,3.50,3510,7200,2.0,0,0,...,9,2600,910,2009,0,98136,47.5537,-122.398,2050,6200

# Q10) Find the MEDIAN living space (sqft_living) of houses with condition = 5

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  int64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(4), int64(16), object(1)
memory usage: 3.5+ MB

In [94]:
Q10 = df[df['condition'] == 5]['sqft_living']
Q10

3        1960
25       1710
27       1400
49       2753
62       2519
         ...
19604    1480
19620    3900
19873    1400
19905    2270
21303    1150
Name: sqft_living, Length: 1701, dtype: int64

In [96]:
Q10.median()

1880.0

# Q11) Which year has the highest no of houses built?

In [99]:
df['yr_built'].value_counts()

yr_built
2014    559
2006    454
2005    450
2004    433
2003    422
       ...
1933     30
1901     29
1902     27
1935     24
1934     21
Name: count, Length: 116, dtype: int64

In [100]:
df['yr_built'].value_counts().idxmax()

np.int64(2014)

# Q12) Compare the average price of houses with waterfront view vs without waterfront view

In [103]:
df['waterfront'].value_counts()

waterfront
0    21450
1      163
Name: count, dtype: int64

In [109]:
without_waterfront_view = df[df['waterfront'] == 0]['price'].mean().round(2)
without_waterfront_view

np.float64(531563.6)

In [110]:
waterfront_view = df[df['waterfront'] == 1]['price'].mean().round(2)
waterfront_view

np.float64(1661876.02)

In [111]:
diff = waterfront_view - without_waterfront_view
diff

np.float64(1130312.42)

# Q13) Find the maximum lot size (lot_size) of houses with 2 or fewer bedrooms

In [113]:
less_than_3_bedrooms = df[df['bedrooms'] <= 2]
less_than_3_bedrooms

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
11,9212900260,20140527T000000,468000,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
18,16000397,20141205T000000,189000,2,1.00,1200,9850,1.0,0,0,...,7,1200,0,1921,0,98002,47.3089,-122.210,1060,5095
23,8091400200,20140516T000000,252700,2,1.50,1070,9643,1.0,0,0,...,7,1070,0,1985,0,98030,47.3533,-122.166,1220,8386
31,2426039314,20141201T000000,280000,2,1.50,1190,1265,3.0,0,0,...,7,1190,0,2005,0,98133,47.7274,-122.357,1390,1756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21586,2767604724,20141015T000000,505000,2,2.50,1430,1201,3.0,0,0,...,8,1430,0,2009,0,98107,47.6707,-122.381,1430,1249
21588,2767600688,20141113T000000,414500,2,1.50,1210,1278,2.0,0,0,...,8,1020,190,2007,0,98117,47.6756,-122.375,1210,1118
21595,1972201967,20141031T000000,520000,2,2.25,1530,981,3.0,0,0,...,8,1480,50,2006,0,98103,47.6533,-122.346,1530,1282
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [116]:
max_lot_size = less_than_3_bedrooms['sqft_lot'].max()
max_lot_size

1164794

# Q13) Identify the zipcode with the highest average price. 

In data analysis, "highest" simply means the largest numerical value (the maximum).When a question asks for the "highest average price," it wants you to do two steps:Find the average (mean) price for every single zipcode.Look at all those averages and pick the largest number among them.A Simple Visual ExampleImagine your dataset has three zipcodes with the following house prices:Zipcode A: $100,000 and $200,000 → Average Price = $150,000Zipcode B: $400,000 and $500,000 → Average Price = $450,000Zipcode C: $200,000 and $300,000 → Average Price = $250,000In this scenario:The averages are $150,000, $450,000, and $250,000.The highest average is $450,000.Therefore, the answer to the question is Zipcode B.How Pandas Finds the "Highest"In the pandas code provided earlier, the function .idxmax() is what looks for the highest value.idx stands for index (the zipcode).max stands for maximum (the highest average).If you want to see the whole list ranked from highest to lowest, you use ascending=False:

In [120]:
df.groupby('zipcode')['price'].mean().sort_values(ascending=False)

zipcode
98039    2.160607e+06
98004    1.355927e+06
98040    1.194230e+06
98112    1.095499e+06
98102    9.012582e+05
             ...
98148    2.849086e+05
98001    2.808047e+05
98032    2.512962e+05
98168    2.403284e+05
98002    2.342840e+05
Name: price, Length: 70, dtype: float64

In [124]:
df.groupby('zipcode')['price'].mean().idxmax()

np.int64(98039)